apply plugin: 'java-library'

group = rootProject.group
version = rootProject.version

sourceCompatibility = '1.8'
targetCompatibility = '1.8'

repositories {
    mavenCentral()
}

dependencies {
    api project(':deathnote-platform-api')
}

sourceSets {
    main {
        java {
            srcDirs = ['../../../../deathnote-core/src/main/java']
        }
    }
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}
