plugins {
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
}

version = project.version
group = project.group

base {
    archivesName = 'deathnote-forge-1.20.1'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

minecraft {
    mappings channel: 'official', version: '1.20.1'
    copyIdeResources = true

    runs {
        configureEach {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'info'
            mods {
                deathnote {
                    source sourceSets.main
                }
            }
        }
        client { }
        server {
            args '--nogui'
        }
    }
}

dependencies {
    minecraft "net.minecraftforge:forge:${forgeVersion1201}"
    implementation project(':deathnote-core')
    implementation project(':deathnote-config-common')
}

def embedProjects = [':deathnote-core', ':deathnote-platform-api', ':deathnote-config-common']

tasks.named('jar', Jar).configure {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    embedProjects.each { path ->
        dependsOn path + ':jar'
        from(zipTree(project(path).tasks.jar.archiveFile)) {
            exclude 'META-INF/*.SF', 'META-INF/*.DSA', 'META-INF/*.RSA'
        }
    }
    manifest {
        attributes([
                'Specification-Title'   : 'deathnote',
                'Specification-Vendor'  : 'yaazyy',
                'Specification-Version' : '1',
                'Implementation-Title'  : project.name,
                'Implementation-Version': archiveVersion.get()
        ])
    }
    finalizedBy 'reobfJar'
}

tasks.named('processResources', ProcessResources).configure {
    def props = [
            'minecraft_version'      : '1.20.1',
            'minecraft_version_range': '[1.20.1,1.21)',
            'forge_version'          : '47.2.0',
            'forge_version_range'    : '[47,)'
    ]
    inputs.properties props
    filesMatching('META-INF/mods.toml') {
        expand props
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
