modLoader = "javafml"
loaderVersion = "[36,)"
license = "All Rights Reserved"

[[mods]]
modId = "deathnote"
version = "1.0.0"
displayName = "Death Note"
description = "A craftable Death Note. Write a player's name, click Done, fate is sealed."
authors = "yaazyy"

[[dependencies.deathnote]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.deathnote]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
